### ISSUE TITLE
Endless mode softlock

### ISSUE THREAD

**Issue by FlooffyBoi** [devyndamonster/PMCPete#1]
I finished the fifth hold on endless mode and the game softlocked. The enemy spawns were disabled and the red barriers were still  there but the hold did not end. I don't know if this caused the issue, but I failed to destroy the encryption things in time and the things did not respawn. 
![20211030193132_1](https://user-images.githubusercontent.com/51369165/139545902-f6259527-eaaf-45c5-bedc-88ceb4be06a7.jpg)
Here's the log:
[LogOutput.log](https://github.com/devyndamonster/PMCPete/files/7447364/LogOutput.log)

**Comment by devyndamonster** [comment]
Endless mode is currently not implemented for PMC Pete, but will be added in a future update

**Comment by devyndamonster** [comment]
Closing this issue as I added basic endless mode level
